name: Build translation pack
on:
  repository_dispatch:
    types: [translation-pack]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources from Locales repository
      uses: actions/checkout@v2
      with:
        path: sources/MostLocales

    - name: Checkout sources from DSL repository
      uses: actions/checkout@v2
      with:
        repository: Guite/MostTextual
        token: ${{ secrets.ACCESS_MOST_PRODUCT }}
        path: sources/MostTextual

    - name: Checkout sources from Generator repository
      uses: actions/checkout@v2
      with:
        repository: Guite/MostGenerator
        path: sources/MostGenerator

    - name: Checkout sources from UI repository
      uses: actions/checkout@v2
      with:
        repository: Guite/MostUi
        token: ${{ secrets.ACCESS_MOST_PRODUCT }}
        path: sources/MostUi

    - name: Checkout sources from Help repository
      uses: actions/checkout@v2
      with:
        repository: Guite/MostHelp
        path: sources/MostHelp

    - name: Checkout sources from Product repository
      uses: actions/checkout@v2
      with:
        repository: Guite/MostProduct
        token: ${{ secrets.ACCESS_MOST_PRODUCT }}
        path: sources/MostProduct

    - name: Build
      run: ./sources/MostLocales/.github/scripts/buildTranslationPack.sh

    # see https://github.com/SamKirkland/FTP-Deploy-Action
    - name: Deploy archive
      uses: SamKirkland/FTP-Deploy-Action@master
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: MostTranslationPack/
        server-dir: translation-template/
        dangerous-clean-slate: true
