name: Build translation pack
on:
  repository_dispatch:
    types: [translation-pack]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources from Locales repository
      uses: actions/checkout@v2
      with:
        path: sources/MostLocales

    - name: Checkout sources from DSL repository
      uses: actions/checkout@v2
      with:
        repository: Guite/MostTextual
        token: ${{ secrets.ACCESS_MOST_PRODUCT }}
        path: sources/MostTextual

    - name: Checkout sources from Generator repository
      uses: actions/checkout@v2
      with:
        repository: Guite/MostGenerator
        path: sources/MostGenerator

    - name: Checkout sources from UI repository
      uses: actions/checkout@v2
      with:
        repository: Guite/MostUi
        token: ${{ secrets.ACCESS_MOST_PRODUCT }}
        path: sources/MostUi

    - name: Checkout sources from Help repository
      uses: actions/checkout@v2
      with:
        repository: Guite/MostHelp
        path: sources/MostHelp

    - name: Checkout sources from product repository
      uses: actions/checkout@v2
      with:
        repository: Guite/MostProduct
        token: ${{ secrets.ACCESS_MOST_PRODUCT }}
        path: sources/MostProduct

    - name: Build
      run: ./sources/MostLocales/.github/scripts/buildTranslationPack.sh

    # see https://github.com/SamKirkland/FTP-Deploy-Action
    - name: Deploy archive
      #uses: SamKirkland/FTP-Deploy-Action@master
      #with:
        #ftp-server: ftp://${{ secrets.FTP_SERVER }}/translation-template/
        #ftp-username: ${{ secrets.FTP_USERNAME }}
        #ftp-password: ${{ secrets.FTP_PASSWORD }}
        #local-dir: MostTranslationPack
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        LOCAL_DIR: MostTranslationPack
        REMOTE_DIR: translation-template
        ARGS: --delete --continue --ignore-time
